fix: update type-checking and user auth
bryantryoung/magic-music-recs pull request #3
Opened 2023-08-06 19:41 UTC by bryantryoung

### Context
There are a couple critical bugs related to user auth:
- new users cannot interact with the application (all requests are failing) after signing in on the live site 
- token refresh is not working for expired access tokens - once a session expires after an hour, manual sign out / sign in is the only way to fix breaking requests 

There is always a problem with type-checking throughout the application. This worsens the dev experience by limiting type inference when building new components / features. It also introduces the opportunity for bugs to go undetected until runtime, making the debugging process more difficult and unpredictable. 

### Changes
TypeScript
- create standardized types for `Artist` and `Track` to be used throughout the app
- remove all instances of ts hacks like `//@ts-nocheck` and using the `any` type
- update `AudioPlayer` component with accurate types related 
- extend NextAuth type defs to include properties necessary for Spotify OAuth integration 

Auth
- After some research into [quota modes](https://developer.spotify.com/documentation/web-api/concepts/quota-modes) for Spotify apps, I determined I will have to apply for an extension to allow new users which are not manually registered in the dashboard
- created a separate Spotify application using their dashboard for development / testing - all preview urls in Vercel will access these keys, separate from the production site 
- implemented a solution for refreshing expired access tokens using the [pattern recommended by NextAuth](https://authjs.dev/guides/basics/refresh-token-rotation)

2023-08-09 17:30 UTC, ChristianArredondo commented
<img width="293" alt="Screenshot 2023-08-09 at 10 25 20 AM" src="https://github.com/bryantryoung/magic-music-recs/assets/24460948/0ea7ed25-ded1-4a07-b35f-1bbf1e21bb65">

Oof--that is quite a massive PR, lol.

Unless there is a change that impacts dozens of files, I would generally recommend PRs to be under 100 lines of code (LOC), or as small as each logical change/step can be.

For this PR, I would probably break it up into several stacked smaller PRs.

I can review this diff as is, which means it will be more cursory and less meaningful due to the sheer size, or you're welcome to split it up.

2023-08-09 18:06 UTC, ChristianArredondo commented on types/Track.ts
> +} | null;
Is this `| null` here expected?

Seems odd to assume that `Track` is always nullable--this should be up to the consumers to define.

2023-08-09 18:06 UTC, ChristianArredondo commented on types/next-auth.d.ts
For my understanding, why is it necessary for us to redefine `"next-auth"` modules?

2023-08-09 18:06 UTC, ChristianArredondo requested changes
Added a lot of questions and comments, as well as a few items that we should probably address.

Sending back to you to respond/address these :)

2023-08-10 18:32 UTC, bryantryoung commented on app/page.tsx
> +      {/* <div className="xl:-mt-[650px] lg:-mt-[500px] hidden lg:block bg-[url('/layered-waves-purple.svg')] bg-center bg-no-repeat bg-cover aspect-video w-full"></div> */}
No, I will remove. I was playing around with an SVG background for the homepage.

2023-08-10 18:36 UTC, bryantryoung commented on components/related-artist/RelatedArtist.tsx
> +                      setIsPlaying(true);
Interesting. Yeah I think it would be nice to encapsulate the logic for mutating the audio ref directly as well as reflecting that in local state, because it is a little confusing as is. And there may be a bug in there too related to a track attempting to play without audio.

2023-08-10 18:36 UTC, bryantryoung commented on components/related-artist/RelatedArtist.tsx
> +                    className="flex  cursor-pointer justify-start flex-col  hover:bg-[#2c2c2c]  hover:bg-opacity-70 w-full sm:flex-row sm:items-center p-2"
Tailwind for the win haha

2023-08-10 18:37 UTC, bryantryoung commented on components/related-artist/RelatedArtist.tsx
> +          {tracks ? (
Agreed.

2023-08-10 21:06 UTC, ChristianArredondo approved these changes

2023-08-14 21:20 UTC, merged